### ISSUE TITLE
missing file named "strcpy-sse2-unaligned.S" 

### ISSUE THREAD

**Issue by danabanana90** [lpipes/AncestralClust#3]
Hey, 
I tried to run the following command:
`gdb --args ancestralclust -i "${p}/fasta_data/all_CO.fa" -d "${p}/res/" -t "${p}/fasta_data/taxon_list.txt" -n 2`

and got the following error:
Starting program: /usr/local/bin/ancestralclust -i /mnt/data/dana/TRINITY_9_DEC_19/Phylogenetic/ancestralclust/fasta_data/all_CO.fa -d /mnt/data/dana/TRINITY_9_DEC_19/Phylogenetic/ancestralclust/res/ -t /mnt/data/dana/TRINITY_9_DEC_19/Phylogenetic/ancestralclust/fasta_data/taxon_list.txt -n 2[Thread debugging using libthread_db enabled]Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".Number of sequences: 6Number of clusters: 2Number of threads: 1Program received signal SIGSEGV, Segmentation fault.__strcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S:298298     **../sysdeps/x86_64/multiarch/strcpy-sse2-unaligned.S: No such file or directory.**

attached my fasta file (I hav changed the suffix from .fa to .txt in order to be able uploading):   [all_CO.txt](https://github.com/lpipes/AncestralClust/files/5861750/all_CO.txt)
and taxon file: [taxon_list.txt](https://github.com/lpipes/AncestralClust/files/5861753/taxon_list.txt)

**Comment by lpipes** [comment]
The program expects the taxonomy file to be in the following format:

`[fasta header]\t[domain;phylum;class;order;family;genus;species]`

For example, if your input fasta file contains the sequence:

`>KR882711.1
ATAGAAATATATCAGTAGACTTTACAATTTTTTCCCTACATATAGCAGGAATTTCCTCAATTATAGGATCAATTAATATAATTTCATCCATTATTAACATTCGATCAAAATTAATAAATATAAATAAAATTTCTTTATTTTCATGATCAATTATATTAACCTCAATTCTTCTTTTATTATCATTACCAGTACTTGCAGGAGCCATTACAATATTATTATTTGATCGTAATATAAATACTTCTTTTTTTGACCCATCAGGAGGTGGAGACCCAA`

Then the taxonomy file should contain:

`KR882711.1	Eukaryota;Arthropoda;Insecta;Hymenoptera;Diapriidae;NA;Diapriidae sp. BOLD-2016`

The taxonomy file must be in the same order of your input fasta file or else the output taxonomy will be incorrect. Please note that the taxonomy information is not used to create the clusters. It is an optional file. Also I haven't added a check yet to check for line breaks in the input fasta file, so the input file should contain the sequence all in the same line. To convert your file you can use the command:

`sed -i ':a; $!N; /^>/!s/\n\([^>]\)/\1/; ta; P; D' all_CO.txt`

Also, since there are only 6 sequences in your input file, you probably should change the 'number of descendants' option to 1 (which is the -p option). I ran the program using this command:

`ancestralclust -i all_CO.txt -n 2 -p 1`

And the following clusters were output:

>Cluster 0
0	2495nt, >Hb_CONSTANS-like...
1	2119nt, >At_CONSTANS-like...
2	1919nt, >Hv_CONSTANS-like...
>Cluster 1
0	2162nt, >Bd_CONSTANS-like...
1	2287nt, >Os_CONSTANS-like...
2	2132nt, >Ta_CONSTANS-like...
